version: "2"
plugins:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  git-legal:
    enabled: true
exclude_patterns:
- db/
- doc/
- "**/log/"
- "**.log"
- ".idea/"
- ".git/"
- ".DS_Store"
- ".autotest"
- "**/neo4j-ruby-driver_jars.rb"
